apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gatewayName }}
  namespace: {{ .Values.namespace }}
spec:
  gatewayClassName: {{ .Values.gatewayClassName }}
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.listener.port }}
      allowedRoutes:
        namespaces:
          from: Same
