apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ .Values.gatewayName }}-route
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gatewayName }}
  hostnames:
    - {{ .Values.hostname | quote }}
  rules:
{{- range .Values.grpcMethods }}
    - matches:
        - method:
            service: {{ .service }}
            method: {{ .method }}
      backendRefs:
        - name: {{ $.Values.backend.name }}
          port: {{ $.Values.backend.port }}
{{- end }}
